name: templateapp
title: Giana`s Return
version: '1.10'
summary: A worthy UNOFFICIAL sequel of “The Great Giana Sisters” jump and run 
description: |
  Evil Swampy and his followers have stolen the magic ruby, which made it once possible for Giana and Maria to return from their dream.
  Many creatures are after this ruby, but does it really has power, or was it just a coincidence? As this is not bad enough, Swampy fell
  in love at first sight with Giana’s sister Maria and shamelessly kidnapped her. She simply has been at the wrong place at the wrong
  time.You will now have to take on the role of Giana and get back the magic ruby. And most important of all, save your beloved sister 
  Maria and get home save! Good Luck!
base: core20  
grade: stable 
confinement: strict
architectures: [amd64]
compression: lzo
license: Proprietary

layout:
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
    
apps:
  #giana:
  templateapp:
    command: giana/giana_linux64
    desktop: usr/share/applications/giana.desktop
    extensions: [gnome-3-38]
    plugs:
      - audio-playback
      - opengl
      - joystick
      - wayland
      - x11
    
parts:
  get-giana:
    after:
      - desktop-glib-only
    plugin: nil 
    build-packages:
      - wget
      - tar
    override-build: |
      wget https://www.retroguru.com/gianas-return/gianas-return-v.latest-linux.tar.gz   
      tar xvzf gianas-return-v.latest-linux.tar.gz --directory $SNAPCRAFT_PART_INSTALL
            
      chmod +x $SNAPCRAFT_PART_INSTALL/giana/giana_linux64
      
      mkdir -p ${SNAPCRAFT_PRIME}/usr/share/applications
      wget -P ${SNAPCRAFT_PRIME}/usr/share/applications https://raw.githubusercontent.com/digidigital/giana-snap-test/main/giana256.png
            
    override-prime: |
      echo '[Desktop Entry]
      Encoding=UTF-8
      Type=Application
      Name=Giana`s Return
      GenericName=Giana`s Return
      Comment=UNOFFICIAL sequel of “The Great Giana Sisters”
      Exec=templateapp 
      Icon=usr/share/applications/giana256.png
      Terminal=false
      Categories=Games;
      StartupNotify=true' > ${SNAPCRAFT_PRIME}/usr/share/applications/giana.desktop
      
      snapcraftctl prime 
      #Exec=giana -fs
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
    
  packages:
    plugin: nil
    build-packages:
      - dpkg
    stage-packages:  
      - freeglut3 
      - libsdl-mixer1.2 
      - libglu1-mesa
      - libasound2
      - libbsd0
      - libcurl4
      - libgcc1
      - libjpeg62
      - libpulse0
      - libsdl2-2.0-0
      - libstdc++6
      - libvorbisfile3
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxpm4
      - libxxf86vm1
      - zlib1g
    prime:
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man
