name: templateapp
title: Giana`s Return
version: '1.10'
summary: A worthy UNOFFICIAL sequel of “The Great Giana Sisters” jump and run 
description: |
  Evil Swampy and his followers have stolen the magic ruby, which made it once possible for Giana and Maria to return from their dream.
  Many creatures are after this ruby, but does it really has power, or was it just a coincidence? As this is not bad enough, Swampy fell
  in love at first sight with Giana’s sister Maria and shamelessly kidnapped her. She simply has been at the wrong place at the wrong
  time.You will now have to take on the role of Giana and get back the magic ruby. And most important of all, save your beloved sister 
  Maria and get home save! Good Luck!
base: core20  
grade: stable 
confinement: strict
architectures: [amd64]
compression: lzo
license: Proprietary

apps:
  #giana:
  templateapp:
    command: giana/start
    desktop: usr/share/applications/giana.desktop
    extensions: [gnome-3-38]
    plugs:
      - audio-playback
      - opengl
      - joystick
      - wayland
      - x11
    
parts:
  get-giana:
    plugin: nil 
    build-packages:
      - wget
      - tar
    override-build: |
      wget https://www.retroguru.com/gianas-return/gianas-return-v.latest-linux.tar.gz   
      tar xvzf gianas-return-v.latest-linux.tar.gz --directory $SNAPCRAFT_PART_INSTALL

      echo '#!/bin/bash
      SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
      cd $SCRIPT_DIR
      if [[ ! $XAUTHORITY =~ "wayland" ]]
      then
        autorandr --force --save original
      fi
            
      ./giana_linux64 -fs
      
      if [[ ! $XAUTHORITY =~ "wayland" ]]
      then
         autorandr --change original
      fi' > $SNAPCRAFT_PART_INSTALL/giana/start
     
      chmod +x $SNAPCRAFT_PART_INSTALL/giana/start
      
      mkdir -p ${SNAPCRAFT_PRIME}/usr/share/applications
      wget -P ${SNAPCRAFT_PRIME}/usr/share/applications https://raw.githubusercontent.com/digidigital/giana-snap-test/main/giana256.png
            
    override-prime: |
      echo '[Desktop Entry]
      Encoding=UTF-8
      Type=Application
      Name=Giana`s Return
      GenericName=Giana`s Return
      Comment=UNOFFICIAL sequel of “The Great Giana Sisters”
      Exec=templateapp 
      Icon=usr/share/applications/giana256.png
      Terminal=false
      Categories=Games;
      StartupNotify=true' > ${SNAPCRAFT_PRIME}/usr/share/applications/giana.desktop
      
      snapcraftctl prime 
  
  packages:
    plugin: nil
    stage-packages:  
      - freeglut3 
      - libsdl-mixer1.2 
      - libglu1-mesa
      - autorandr
    prime:
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man
